language: php
sudo: false

php:
  - "7.1"
  - "7.2"
  - "7.3"

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - pear config-set preferred_state beta
  - pecl channel-update pecl.php.net
  - yes | pecl install imagick

install:
  - composer install --prefer-dist --no-interaction

script:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; else vendor/bin/phpunit; fi
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then vendor/bin/php-cs-fixer fix --config=vendor/ixocreate/coding-standard/.php_cs -v --dry-run --using-cache=no --path-mode=intersection `git diff --name-only --diff-filter=ACMRTUXB $TRAVIS_COMMIT_RANGE`; fi

after_success:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then php vendor/bin/php-coveralls -v; fi

notifications:
  email: false
  slack:
    secure: "qwOTxsVOLsm6u1+eIG8/H8eDl2rloATctixKdffK/7/NktJcaGJbVV6i8N3UXrqwD+xfF0X3wUzkmkwL1XS6Hyl1fqD+lvOXRUI9W7tZEBU/+9Kj/PkgG4bNG1tTMazwQKO51+X4X5a9S8TNR3OMWMzMB8fy0SFynojCOsNILObKxAlOq8nB8BIcKameJVPTVZlKPgThLvlTLMzf6PNxMzM9dn54v3sMXo93yZVBlwO41h9ZtQlZUu771PadQiE5saVdgcBrFwiqJ5Q1QjkkQWAh6/3J3C0lowTViGgfqgjZTgxa1gBKjslQ+31fXXv1N+yU007nsSchJibhNRQmbR6dC4U5fy6mzmW0AOdzKWWYXB2t8MyMNzFA9cXPmlIBpeMYsxVfC7+SSDe6xAGJ+dK7/9h+qmvvVYuN+SRrbeyiIrynDxdwwXYnYa0f3Rs9FZC3z7nvUr0MBbtIc1q/ZirUemeuBw9c+MQ4imsvAno0YH6RuJLaXQbqUqzmQorDXanq4j1rcz4UGouQTd0kJHG+HUrsWkRcTnkua9YHnf9dmNRDKx+TlXLjVF1OinrdN+SidzspBBnsm3r6rkXMgWpxysd3nBHcqa0FRqOEIDTQt9j39aWmCJjBUO1ww2tKigZSY+nufU2LXGziD1hQq41R/5grKrOw601V2rJGCfI="
